# Homework 1

##### 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
import numpy as np
a=np.arange(11)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


##### 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [3]:
m = np.zeros((3, 3), dtype="u4")
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


##### 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [4]:
m=np.random.randint(1, 10, (5, 5))
print(m)

[[5 3 6 7 2]
 [7 1 7 7 1]
 [7 3 7 3 9]
 [2 2 2 2 2]
 [1 1 5 7 4]]


##### 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [6]:
m=np.random.random((4, 4))
print(m)

[[0.51915409 0.20542641 0.5003035  0.85948738]
 [0.8375046  0.33296861 0.50725707 0.6242107 ]
 [0.11680369 0.48456532 0.80158879 0.09285706]
 [0.72958408 0.13485616 0.29698361 0.89603164]]


##### 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [74]:
a=np.random.randint(1, 10, 5)
b = np.random.randint(1, 10, 5)
print(f'The first vector: {a}')
print(f'The second vector: {b}')
print(f'Sum: {a+b}')
print(f'Subtraction: {a-b}')
print(f'Product: {a*b}')

The first vector: [8 6 4 3 6]
The second vector: [2 2 5 9 1]
Sum: [10  8  9 12  7]
Subtraction: [ 6  4 -1 -6  5]
Product: [16 12 20 27  6]


##### 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [55]:
a = np.random.randint(1, 10, 7)
b = np.random.randint(1, 10, 7)
print(f"The first vector: {a}")
print(f"The second vector: {b}")
print(f"Scalar product: {np.dot(a, b)}")

The first vctor: [3 8 7 5 5 3 6]
The second vector: [7 3 1 8 4 8 1]
Scalar product: 142


##### 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [76]:
a=np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 3))
print(f"The first matrix:\n{a}")
print(f"The second matrix:\n{b}")
print(f'Product of two matrixes:\n{np.dot(a, b)}')

The first matrix:
[[8 6]
 [1 9]]
The second matrix:
[[5 1 1]
 [7 3 2]]
Product of two matrixes:
[[82 26 20]
 [68 28 19]]


##### 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [59]:
a = np.random.randint(1, 10, (3, 3))
a_inv = np.linalg.inv(a)
print(f'Original matrix:\n{a}')
print(f'Inverse matrix:\n{a_inv}')

Original matrix:
[[6 3 1]
 [5 6 3]
 [7 5 1]]
Inverse matrix:
[[ 0.39130435 -0.08695652 -0.13043478]
 [-0.69565217  0.04347826  0.56521739]
 [ 0.73913043  0.39130435 -0.91304348]]


##### 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [60]:
a = np.random.randint(0, 10, (4, 4))
print(f'Original matrix:\n{a}')
print(f"Transponed matrix:\n{a.T}")

Original matrix:
[[5 4 8 7]
 [0 8 7 5]
 [1 6 8 8]
 [2 1 9 3]]
Transponed matrix:
[[5 0 1 2]
 [4 8 6 1]
 [8 7 8 9]
 [7 5 8 3]]


##### 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [77]:
a = np.random.randint(1, 10, (4, 4))
b = np.random.randint(1, 10, 4)
print(f'Matrix:\n{a}')
print(f'Vector: {b}')
print(f'Product of vector and matrix:\n{np.dot(a, b)}')

Matrix:
[[6 2 2 9]
 [7 7 2 4]
 [6 4 6 3]
 [3 8 6 3]]
Vector: [9 9 3 6]
Product of vector and matrix:
[132 156 126 135]


##### 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [78]:
a = np.random.random((2, 3))
b = np.random.random((3,))
print(f"Matrix:\n{a}")
print(f"Vector: {b}")
print(f"Product of vector and matrix:\n{np.dot(a, b)}")

Matrix:
[[0.15285985 0.73803567 0.39709698]
 [0.95439461 0.34923437 0.40720502]]
Vector: [0.03680728 0.60531848 0.35976056]
Product of vector and matrix:
[0.59523282 0.393023  ]


##### 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [65]:
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))
print(f"The first matrix:\n{a}")
print(f"The second matrix:\n{b}")
print(f"Product of two matrixes by elements:\n{a*b}")

The first matrix:
[[6 3]
 [4 8]]
The second matrix:
[[2 3]
 [1 4]]
Product of two matrixes by elemnts:
[[12  9]
 [ 4 32]]


##### 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [66]:
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))
print(f"The first matrix:\n{a}")
print(f"The second matrix:\n{b}")
print(f"Product of two matrixes by elements:\n{np.dot(a, b)}")

The first matrix:
[[7 1]
 [3 1]]
The second matrix:
[[2 3]
 [6 8]]
Product of two matrixes by elements:
[[20 29]
 [12 17]]


##### 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [67]:
a = np.random.randint(1, 100, (5, 5))
print(f'The matrix:\n{a}')
print(f'Sum of matrix elements:\n{a.sum()}')

The matrix:
[[79 57 62 31 43]
 [62 67 37 14 69]
 [58 49 37 73 70]
 [ 5 71 70 19 97]
 [ 1 80 97  5 95]]
Sum of matrix elements:
1348


##### 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [68]:
a = np.random.randint(1, 10, (4, 4))
b = np.random.randint(1, 10, (4, 4))
print(f"The first matrix:\n{a}")
print(f"The second matrix:\n{b}")
print(f"Subtraction of two matrixes:\n{a-b}")

The first matrix:
[[5 9 4 9]
 [3 3 3 7]
 [3 2 9 6]
 [4 9 8 1]]
The second matrix:
[[1 8 7 7]
 [4 5 8 2]
 [6 9 5 1]
 [1 6 8 5]]
Subtraction of two matrixes:
[[ 4  1 -3  2]
 [-1 -2 -5  5]
 [-3 -7  4  5]
 [ 3  3  0 -4]]


##### 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [79]:
a = np.random.random((3, 3))
b=[]
for i in range(3):
    b.append(a[i].sum())
print(f'The matrix:\n{a}')
print(f"Vertical vector, built from sums:\n{np.array(b).reshape(-1, 1)}")

The matrix:
[[0.33655652 0.87887606 0.34046419]
 [0.03704016 0.92253464 0.93913747]
 [0.75601941 0.45929929 0.58590833]]
Vertical vector, built from sums:
[[1.55589677]
 [1.89871227]
 [1.80122704]]


##### 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [71]:
a=np.random.randint(1, 10, (3, 4))
print(f'The matrix;\n{a}')
print(f'The square of that matrix:\n{a**2}')

The matrix;
[[1 7 8 5]
 [8 2 5 5]
 [7 2 6 2]]
The square of that matrix:
[[ 1 49 64 25]
 [64  4 25 25]
 [49  4 36  4]]


##### 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [72]:
a=np.random.randint(1, 50, 4)
print(f'The vector:{a}')
print(f'Sqaure root of that vector:\n{a**0.5}')

The vector:[28 41 38 26]
Sqaure root of that vector:
[5.29150262 6.40312424 6.164414   5.09901951]
